package com.epam.poc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-29T17:43:42.625+03:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://www.olegbook.com/BookService/", name = "BookService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BookService {

    @WebMethod(operationName = "GetAllBooks", action = "http://www.olegbook.com/BookService/GetAllBooks")
    @WebResult(name = "GetAllBooksResponse", targetNamespace = "http://www.olegbook.com/BookService/", partName = "parameters")
    public GetAllBooksResponse getAllBooks(

        @WebParam(partName = "parameters", name = "GetAllBooks", targetNamespace = "http://www.olegbook.com/BookService/")
            GetAllBooks parameters
    );

    @WebMethod(operationName = "AddBook", action = "http://www.olegbook.com/BookService/AddBook")
    @WebResult(name = "AddBookResponse", targetNamespace = "http://www.olegbook.com/BookService/", partName = "parameters")
    public AddBookResponse addBook(

        @WebParam(partName = "parameters", name = "AddBook", targetNamespace = "http://www.olegbook.com/BookService/")
            AddBook parameters
    );

    @WebMethod(operationName = "GetBook", action = "http://www.olegbook.com/BookService/GetBook")
    @WebResult(name = "GetBookResponse", targetNamespace = "http://www.olegbook.com/BookService/", partName = "parameters")
    public GetBookResponse getBook(

        @WebParam(partName = "parameters", name = "GetBook", targetNamespace = "http://www.olegbook.com/BookService/")
            GetBook parameters
    );
}
